import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

const inter = Inter({ subsets: ["latin"] });

<<<<<<< Updated upstream
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
=======
  export const metadata: Metadata = {
    title: "BeFit",
    description: "BeFit site",
  };
>>>>>>> Stashed changes

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
